import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import './CombinedRisk.css';

const CombinedRisk = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState(null);
  const [fusionData, setFusionData] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchCombinedRisk = async () => {
      try {
        const sessionId = localStorage.getItem('cbir_session_id');

        if (!sessionId || sessionId.startsWith('sess_')) {
          if (sessionId && sessionId.startsWith('sess_')) {
            localStorage.removeItem('cbir_session_id');
          }
          setErrorMsg("No active session found or session invalid. Please complete the Risk Screener and Image Matcher first.");
          setIsLoading(false);
          return;
        }

        const res = await fetch('http://127.0.0.1:8000/combined-risk', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ session_id: sessionId })
        });

        if (res.status === 200) {
          const data = await res.json();
          setFusionData(data);
          setIsLoading(false);
        } else if (res.status === 422) {
          setErrorMsg("Session is incomplete. Both the Risk Screener and Image Matcher must be completed before a combined result can be generated.");
          setIsLoading(false);
        } else if (res.status === 404) {
          setErrorMsg("Session not found on server. Please start a new session.");
          setIsLoading(false);
        } else {
          setErrorMsg(`Server error (${res.status}). Please try again later.`);
          setIsLoading(false);
        }
      } catch (err) {
        setErrorMsg("Network error: " + err.message);
        setIsLoading(false);
      }
    };

    fetchCombinedRisk();
  }, []);

  const getUrgencyClass = (urgency) => {
    if (!urgency) return 'muted';
    const lower = urgency.toLowerCase();
    if (lower.includes('urgent') || lower.includes('high')) return 'high';
    if (lower.includes('monitor') || lower.includes('moderate')) return 'moderate';
    if (lower.includes('routine') || lower.includes('low')) return 'low';
    return 'muted';
  };

  if (isLoading) {
    return (
      <div className="combined-risk-container loading">
        <div className="spinner"></div>
      </div>
    );
  }

  if (errorMsg) {
    return (
      <div className="combined-risk-container">
        <div className="error-card">
          <span className="error-icon">⚠️</span>
          <h2>Incomplete Triage</h2>
          <p>{errorMsg}</p>
          <div className="action-buttons">
            <button onClick={() => navigate('/questionnaire')} className="btn btn-outline">Risk Screener</button>
            <button onClick={() => navigate('/matcher')} className="btn btn-outline">Image Matcher</button>
          </div>
        </div>
      </div>
    );
  }

  const urgencyClass = getUrgencyClass(fusionData?.urgency);

  return (
    <div className="combined-risk-container">
      <div className="result-content">
        <h1>Combined Triage Result</h1>
        <p className="subtitle">This synthesis fuses your questionnaire responses and image analysis for a comprehensive assessment.</p>

        <div className={`result-card urgency-${urgencyClass}`}>
          <div className="urgency-badge">
            {fusionData?.urgency?.toUpperCase() || 'UNKNOWN'}
          </div>
          <h2 className="risk-label">{fusionData?.combined_risk_label || 'Unknown Risk'}</h2>
          <p className="recommendation">{fusionData?.recommendation || 'Please consult a clinician.'}</p>
        </div>

        <div className="disclaimer-box">
          <span className="info-icon">ℹ️</span>
          <p>This result is generated by an AI assistant for research purposes. It is not a definitive medical diagnosis. Always rely on a qualified oral health specialist for final clinical judgment.</p>
        </div>
      </div>
    </div>
  );
};

export default CombinedRisk;
